### ISSUE TITLE
Doubts about the `ignore_last_attn` parameter

### ISSUE THREAD

**Issue by chinmay5** [kakaobrain/tcl#1]
Thank you so much for releasing the code base and your wonderful work. I was going through the code base and I am struggling a bit with the parameter `ignore_last_attn`. Can you please explain what is its purpose? I am a bit confused since if all entries except the diagonal are masked away, how does it work?

**Comment by khanrc** [comment]
Thank you for your interest in our work.

The `ignore_last_attn` option is an implementation of MaskCLIP (https://link.springer.com/chapter/10.1007/978-3-031-19815-1_40). They enable open-world segmentation by removing the last attention from a pre-trained CLIP model. We employ this technique as an initializer of our model.

**Comment by chinmay5** [comment]
Thank you so much for your quick response. Just to confirm, we are putting a mask in this layer so that the self-attention layer does not perform multi-head attention with other tokens (because we have only a diagonal mask activated). So, it only performs the linear projections of query-key and value vectors. Finally, we would directly use the projected results. Thanks.

**Comment by khanrc** [comment]
Yes, that's correct.
