### ISSUE TITLE
Do you mind publishing your training log for reference?

### ISSUE THREAD

**Issue by yxchng** [kakaobrain/tcl#2]

**Comment by khanrc** [comment]
We do not have the training log for the official checkpoint. If It helps much, we can provide the log by re-training. Will that help much?

**Comment by yxchng** [comment]
yes it will. thanks a lot!

**Comment by khanrc** [comment]
[log.txt](https://github.com/kakaobrain/tcl/files/11589180/log.txt)

Hope this help.
