### ISSUE TITLE
CXR-CLIP code is not found

### ISSUE THREAD

**Issue by SaikaOfficial** [kakaobrain/tcl#3]
I was unable to find the relevant code through given link in paper "CXR-CLIP: Toward Large Scale Chest X-ray Language-Image Pre-training" and your repository list. I badly want the code, where can I find it?

**Comment by khanrc** [comment]
I'm not the author of the paper, but I asked my colleague who is. The code hasn't been released yet, but it's expected to be available within a month. For more details, you can contact [kyle.you@kakaobrain.com](mailto:kyle.you@kakaobrain.com).

**Comment by SaikaOfficial** [comment]
> I'm not the author of the paper, but I asked my colleague who is. The code hasn't been released yet, but it's expected to be available within a month. For more details, you can contact [kyle.you@kakaobrain.com](mailto:kyle.you@kakaobrain.com).

Thanks!
