### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Wyh987654321** [kakaobrain/tcl#4]
Dear author, I encountered a problem while training the model. No matter how I modified my configuration parameters, I was unable to obtain data through the dataloader when using GCC12m for training, and the algorithm got stuck endlessly at this stage. If you could give me some guidance on this issue, I would greatly appreciate it.

**Comment by khanrc** [comment]
Thank you for your interest in our research. We recommend checking your library versions and environments first.

**Comment by Wyh987654321** [comment]
Thank you for your suggestion, but it doesn't seem to be an environmental issue because my code can successfully train on the cc3m dataset, but switching to cc12m won't work.

**Comment by khanrc** [comment]
If so, it might be worth checking if there's an issue with the cc12m dataset.
