### ISSUE TITLE
About training cost.

### ISSUE THREAD

**Issue by Colezwhy** [kakaobrain/tcl#6]
Hi, thank you for your wonderful work!
And I was wondering the training cost of TCL. In the paper it writes 12 hours, but what GPUs are you using?

**Comment by khanrc** [comment]
We use V100 x 16 GPUs. Note that the training cost is measured with an ideal network setting (e.g., Infiniband); the network is a common bottleneck in multinode setting.

**Comment by Colezwhy** [comment]
Thank you, and I will close this issue.
